modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="gregdustry"
version="0.69.5"
displayName="The Diffy Experience - Gregified"
displayURL="https://www.youtube.com/@DiffyMC"
logoFile="logo.png"
credits="Diffy"
authors="IDoTheHax"
description="unfortunately there doesn't appear to be a license that would prevent you from legally uninstalling this mod after playing it. also subscribe to diffymc right now or be eaten by a cow"

[[dependencies.gregdustry]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="AFTER"
side="BOTH"

[[dependencies.gregdustry]]
modId="geckolib"
mandatory=false
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.gregdustry]]
modId="the_diffy_experience"
mandatory=true
versionRange="[0.69.4]"
ordering="NONE"
side="BOTH"

